FORMAT: 1A

# BoomBox
Use a raspberry pi or any computer as a media server for audio files.

# Data Structures

## Song Track (object)
+ id: 1 (number,required)
+ name: Mama Tried (string,required)
+ filename: /audio/merle/mama-tried/01.ogg (string,required)
+ albumid: 1 (number)

## Song Album (object)
+ id: 1 (number,required)
+ artistid: 1 (number,required)
+ name: A Portrait of Merle Haggard (string)
+ genre: Country

## Song Artist (object)
+ id: (number,required)
+ name: Merle Haggard (string,required)

# Group Tracks
Manage song tracks

## Song track collection [/track]

### List one or all songs [GET /track[/{id}]]
Search song collection, paginate by limit and page parameters, or limit by id.
+ Parameters 
  + search (number,optional) - keyword or phrase to search for
  + limit (number,optional) - maximum number of items to retrieve
    + Default: 25
  + page (number,optional) - retrieve nth page of {limit} items
    + Default: 1
+ Response 200 (application/json)
  + Attributes (array[Song Track])
### Insert song [POST /track/{id}]
Save information about an audio track. This does not include the capability to upload/save the file to the hard drive! Which means that the file must already exist.
+ Response 201
+ Attributes (array[Song Track])
### Update song [PUT /track/{id}]
Update a field or set of fields concerning a given audio track.
+ Response 204
### Delete song [DELETE /track/{id}]
Removes the information concerning a given audio track from the database. Note this will not delete the file from the hard drive!
+ Response 204

# Group Albums
Manage song albums.

## Song album collection [/album]

### List one or all albums [GET /album[/{id}]]
Search album collection, paginate by limit and page parameters, or limit by id.
+ Parameters 
  + search (number,optional) - keyword or phrase to search for
  + limit (number,optional) - maximum number of items to retrieve
    + Default: 25
  + page (number,optional) - retrieve nth page of {limit} items
    + Default: 1
+ Response 200 (application/json)
  + Attributes (array[Song Album])
### Insert album [POST /album/{id}]
Save information about a new album.
+ Response 201
+ Attributes (array[Song Album])
### Update album [PUT /album/{id}]
Update a field or set of fields concerning a given album.
+ Response 204
### Delete album [DELETE /album/{id}]
Removes the information concerning a given album from the database.
+ Response 204

# Group Artists
Manage song artists.

## Song artist collection [/artist]

### List one or all artists [GET /artist[/{id}]]
Search artists collection, paginate by limit and page parameters, or limit by id.
+ Parameters 
  + search (number,optional) - keyword or phrase to search for
  + limit (number,optional) - maximum number of items to retrieve
    + Default: 25
  + page (number,optional) - retrieve nth page of {limit} items
    + Default: 1
+ Response 200 (application/json)
  + Attributes (array[Song Artist])
### Insert artist [POST /album/{id}]
Save information about a new artist.
+ Response 201
+ Attributes (Song Artist)
### Update artist [PUT /album/{id}]
Update a field or set of fields concerning a given artist.
+ Response 204
### Delete artist [DELETE /album/{id}]
Removes the information concerning a given artist from the database.
+ Response 204

# Group Stream
Manage the audio stream. Includes play, pause, and choosing resources to play, such as a track or album or list of songs by artist.

## Stream audio [/stream]

### Stream song [GET /stream/track/{id}]
Play a given song, indicated by the id in the url.
+ Attributes
  + repeat (boolean) - if true, infinitely loops the song track
    + Default: false

### Stream album [GET /stream/album/{id}]
Play all songs from a given album, indicated by the id in the url.
+ Attributes
  + shuffle (boolean) - if true, randomizes play order of tracks by artist
    + Default: false
  + repeat (boolean) - if true, infinitely loops the song tracks
    + Default: false

### Stream artist [GET /stream/artist/{id}]
Play all songs by a given artist, indicated by the id in the url.
+ Attributes
  + shuffle (boolean) - if true, randomizes play order of tracks by artist
    + Default: false
  + repeat (boolean) - if true, infinitely loops the song tracks
    + Default: false

### Pause audio stream [GET /stream/pause]
Gracefully halts the audio stream. (duh, y'all should know what "pause" means!)
+ Response 200

### Resume audio stream [GET /stream/play]
If the audio stream is currently paused, resume playing the current resource.
+ Response 200
